---
title: "Playful Test"
subtitle: "Week 1 Notes in R"
author: "Randi Bolt"
output:
   html_document:
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Notes
#### Conditionals - Nesting

```{r}
x = 3
if (x < 0){
  "Negative"
} else if (x > 0) {
  "Positive"
} else {
  "Zero"
}
```

Notices else if is on the same line as the closing of the {}. That is because else is apart of the if statement. It isn't a function by itself. 

#### Conditionals - Error Checking
stop and stopifnot function 
```{r, error=TRUE}
ok <- False
if (!ok)
  stop("Thinkgs are not ok.")
```

```{r, error=TRUE}
stopifnot(ok)
```

#### Set 1 - Exercise 1
```{r, error=TRUE}
x <- 3
y <- 3
if ((x%%2) == 1 & (y%%2) == 0){
  stop("Error Message.")
}else{
  if(x > 3){
    if(y <= 3){
      print("Hello World!")
    }else{
      print("!dlroW olleH")
    }
  }else{
    print("Something else. . .")
  }
}
```

```{r}
res = c()
for(x in 1:10){
  res=c(res,x^2)
}
res
```
```{r}
res = c()
for( y in list(1:3, LETTERS[1:7],c(TRUE,FALSE))){
  res = c(res, length(y))
}
res

i = 1
res = rep(NA,10)

while(i<10){
  res[i] = i^2
  i=i+1
}

res
```
#### Loops - repeat loops
```{r}
i =1 
res = rep(NA,10)

repeat{
  res[i]= i^2
  i = i+1
  if (i > 10){
    break
  }
}
res
```
#### NA , NAN and NULL
```{r}
a = NA
length(a)
b = NaN
length(NaN)
c = NULL
length(NULL)
```
#### Loops break and next
```{r}
res = c()
for(i in 1:10){
  if(i%%2 == 0)
    break
  res = c(res,i)
  print(res)
}

rat = c()
for(i in 1:10){
  if(i %% 2 == 0)
    next
  rat = c(rat,i)
  print(rat)
}
```
#### Loops - nested loops
```{r}
res <- c()
for(x in 1:2){
  for (y in 3:0){
    res =c(res, (x^2-y))
  }
}
res
```
#### example 2
```{r}
res <- c()
i <- 1
while(i < 5){
  j <- 1
  while(j <4){
    res <- c(res, i+j)
    j <- j+1
  }
  i <- i+1 
}
res
```
#### helper functions
```{r}
4 :7
length(4:7)
seq(4,7)
seq_along(4:7)
seq_len(length(4:7))
seq(4,7,by=2)
```

#### Set 1 - Exercise 2
```{r}
primes = c(2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97)
x = c(3, 4, 12, 19, 23, 51, 61, 63, 78)

res <- c()
j <- 1
b <- x[1]

for(a in primes){
  if(j>length(x)){
    break
  }
  while( (b<=a) & (j<= length(x)) ){
    if(b!=a){
      res <- c(res,b)
    }
    j <- j+1
    b <- x[j]
  }
}
res
```

